version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    environment:
      APP_ENV: dev
    depends_on:
      - db
      - mailpit
      - apache
      - node

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: symfony
      POSTGRES_USER: symfony
      POSTGRES_PASSWORD: symfony
    volumes:
      - pgdata:/var/lib/postgresql/data

  mailpit:
    image: axllent/mailpit
    ports:
      - "8025:8025"
      - "1025:1025"

  node:
    image: node:18
    working_dir: /app
    volumes:
      - .:/app
    command: tail -f /dev/null

  apache:
    image: httpd:2.4
    ports:
      - "8081:80"
    volumes:
      - ./public:/usr/local/apache2/htdocs/

volumes:
  pgdata: